### ISSUE TITLE
Improve search performance in order to not be limited by 50 search results

### ISSUE THREAD

**Issue by hallgeirl** [hallgeirl/grim-search#12]
Possible solutions:
- Using Lucene and paging (preferably infinite scrolling)
- Simply implementing paging with what already exists (but it's a dumb search currently, would be nice to improve)

**Comment by marius00** [comment]
Suffered a lot with performance issues with IA, but finally got it "under control".

In-Memory or using a proper embedded SQL server it was fine, but using SQLite it suffered badly.
Now searches are running just fine, can do any search near instantly, but "applying stats to items", eg fetching them all and providing them in a human readable format.. that's a concern.

IA matches your items to your search criterias, and then it paginates the stat application.
That said, it was a semi bumpy road getting there.

For your needs (mules etc) it should be doable a bit easier, since players wont have 7-20,000 items on mules.

**Comment by hallgeirl** [comment]
This is implemented in v0.4.0.

**Comment by hallgeirl** [comment]
Full support for continuous/infinite scrolling introduced in 0.4.1. Note that it's actually not paged on the search end -- search results are returned in one bulk. But it turned out it's the UI update that was slow, so just paging on what's actually shown seems to perform quite well.
